wandb_version: 1

seed:
  desc: null
  value: 42
output_dir:
  desc: null
  value: ./output/hpt_train
domains:
  desc: null
  value: Robotwin
wb_tag:
  desc: null
  value: hpt_exp
log_interval:
  desc: null
  value: 10
script_name:
  desc: null
  value: hpt_train
pretrained_dir:
  desc: null
  value: ./hpt-xlarge
parallel_eval:
  desc: null
  value: false
task_name:
  desc: null
  value: move_can_pot
task_config:
  desc: null
  value: demo_clean
episode_num:
  desc: null
  value: 100
processed_data_dir:
  desc: null
  value: ./processed_data
total_num_traj:
  desc: null
  value: 100
dataset:
  desc: null
  value:
    _target_: hpt.dataset.local_traj_dataset.LocalTrajDataset
    val_ratio: 0.1
    pad_after: 0
    episode_cnt: 100
    step_cnt: 32000
    data_augmentation: false
    use_disk: true
    pad_before: 0
    data_ratio: 1
    action_horizon: 8
    observation_horizon: 5
    dataset_postfix: _traj100
    image_encoder: resnet
    dataset_encoder_postfix: _resnet
    dataset_name: Robotwin
    precompute_feat: true
    use_multiview: true
    normalize_state: true
    regenerate: false
    action_multiple_horizon: true
    random_mask_obs: true
    data_augment_ratio: 1
    proprioception_expand: false
    proprioception_expand_dim: 32
    env_rollout_fn:
      _target_: policy.HPT.process_data.convert_dataset_robotwin_cached
      task_name: move_can_pot
      task_config: demo_clean
      episode_num: 100
      use_cache: true
      save_dir: ./processed_data
network:
  desc: null
  value:
    _target_: hpt.models.policy.Policy
    embed_dim: 1024
    num_blocks: 32
    num_heads: 8
    drop_path: 0.1
    use_modality_embedding: true
    use_domain_embedding: false
    observation_horizon: 5
    action_horizon: 8
    token_postprocessing: mean
    cross_stem_attention: true
    weight_init_style: pytorch
    no_trunk: false
    finetune_encoder: false
stem:
  desc: null
  value:
    modalities:
    - image
    - state
    modality_embed_dim: 1024
    normalize_state: true
    state_embedding_dim: 14
    cross_attention: true
    precompute_feat: true
    image_encoder: resnet
    crossattn_dim_head: 64
    crossattn_heads: 8
    crossattn_modality_dropout: 0.1
    num_blocks: 1
    observation_horizon: 5
    masked_autoencoding: false
    random_horizon_masking: true
    add_pos_embedding_to_state: false
    crossattn_latent:
      image: 16
      state: 16
      language: 8
    image:
      _target_: hpt.models.policy_stem.MLP
      input_dim: 512
      output_dim: 1024
      widths:
      - 128
      num_of_copy: 1
    state:
      _target_: hpt.models.policy_stem.MLP
      input_dim: 14
      output_dim: 1024
      widths:
      - 128
head:
  desc: null
  value:
    _target_: hpt.models.policy_head.MLP
    input_dim: 1024
    tanh_end: false
    output_dim: 112
    widths:
    - 256
    - 128
    normalize_action: false
    dropout: true
dataloader:
  desc: null
  value:
    batch_size: 256
    num_workers: 4
    pin_memory: true
    persistent_workers: true
    shuffle: true
    drop_last: false
val_dataloader:
  desc: null
  value:
    batch_size: 128
    num_workers: 4
    shuffle: false
    pin_memory: true
    persistent_workers: true
    drop_last: false
optimizer:
  desc: null
  value:
    _target_: torch.optim.Adam
    lr: 0.0001
lr_scheduler:
  desc: null
  value:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 1000
    eta_min: 1.0e-06
train:
  desc: null
  value:
    total_epochs: 1000
    total_iters: 2000000
    epoch_iters: 1000
    validation_iters: 350
    pretrained_dir: ./hpt-xlarge
    freeze_trunk: true
    wandb_pretrained_dir: ''
optimizer_misc:
  desc: null
  value:
    nontrunk_lr_scale: 1.0
warmup_lr:
  desc: null
  value:
    lr: 1.0e-10
    step: 1000
gpu_id:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1756716777.390678
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.18
      5: 0.16.1
      6: 4.36.0
      8:
      - 5
      13: linux-x86_64
